codon_dict = Dict(
    "UUU" => "F",
    "CUU" => "L",
    "AUU" => "I",
    "GUU" => "V",
    "UUC" => "F",
    "CUC" => "L",
    "AUC" => "I",
    "GUC" => "V",
    "UUA" => "L",
    "CUA" => "L",
    "AUA" => "I",
    "GUA" => "V",
    "UUG" => "L",
    "CUG" => "L",
    "AUG" => "M",
    "GUG" => "V",
    "UCU" => "S",
    "CCU" => "P",
    "ACU" => "T",
    "GCU" => "A",
    "UCC" => "S",
    "CCC" => "P",
    "ACC" => "T",
    "GCC" => "A",
    "UCA" => "S",
    "CCA" => "P",
    "ACA" => "T",
    "GCA" => "A",
    "UCG" => "S",
    "CCG" => "P",
    "ACG" => "T",
    "GCG" => "A",
    "UAU" => "Y",
    "CAU" => "H",
    "AAU" => "N",
    "GAU" => "D",
    "UAC" => "Y",
    "CAC" => "H",
    "AAC" => "N",
    "GAC" => "D",
    "UAA" => "S",
    "CAA" => "Q",
    "AAA" => "K",
    "GAA" => "E",
    "UAG" => "S",
    "CAG" => "Q",
    "AAG" => "K",
    "GAG" => "E",
    "UGU" => "C",
    "CGU" => "R",
    "AGU" => "S",
    "GGU" => "G",
    "UGC" => "C",
    "CGC" => "R",
    "AGC" => "S",
    "GGC" => "G",
    "UGA" => "S",
    "CGA" => "R",
    "AGA" => "R",
    "GGA" => "G",
    "UGG" => "W",
    "CGG" => "R",
    "AGG" => "R",
    "GGG" => "G"
)

function prot(rna)
  codons = [rna[i:(i+2)] for i=1:3:(length(rna)-2)]
  aminos = [codon_dict[c] for c=codons]
  amino_string = join(aminos)
  
  amino_string[end] == 'S' ? (return amino_string[1:(end-1)]) : (return amino_string)
end